# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rocket-democracy',
                'doc_host': 'https://robbievz.github.io',
                'git_url': 'https://github.com/robbievz/rocket-democracy',
                'lib_path': 'rocket_democracy'},
  'syms': {'rocket_democracy.core': {'rocket_democracy.core.foo': ('core.html#foo', 'rocket_democracy/core.py')}}}
